---
- name: restart grafana
  systemd:
    name: grafana-server
    daemon_reload: yes
    enabled: yes
    state: restarted
    
- name: restart rsyslog
  systemd:
    name: rsyslog
    daemon_reload: yes
    enabled: yes
    state: restarted
  
- name: restart auditd
  systemd:
    name: auditd
    daemon_reload: yes
    enabled: yes
    state: restarted