
 - name: set up client, server
   template:
     src: ifcfg-vlan1.j2
     dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
     owner: root
     group: root
     mode: 0644

 - name: restart hosts for vlan1
   reboot:
     reboot_timeout: 3600