---
- name: Setup DNS server
  hosts: serverDNS
  become: True
  gather_facts: False
  roles:
    - role: ../roles/dns
      vars:
        repolabel: serverdns
        repopass: Cae^53&gd899
    - ../roles/prometheus-node-exporter
...