version: '3.6'

volumes:
  pg_project:


services:
  pg_db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newspaper
    volumes:
      - pg_project:/var/lib/postgresql/data
      - /tmp/:/tmp/
    networks:
      network:
        ipv4_address: 10.5.0.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newspaper"]
      interval: 15s
      timeout: 10s
      retries: 7
      start_period: 12s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500MB
    
  scrapper:
    container_name: scrapper
    build: .
    image: scrapper

    environment:
      POSTGRES_HOST: pg_db
    tty: true
    volumes:
      - /tmp/:/tmp/
    depends_on:
    - pg_db
    networks:
      network:
        ipv4_address: 10.5.0.7


networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1