global:
  scrape_interval: 15s
  external_labels:
      monitor: 'otuslab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "node_export"
    static_configs:
      - targets: ["localhost:9200"]
      