- name: 'Prepare stands RAS OpenVPN'
  hosts: vpn
  gather_facts: true
  become: yes
  tasks:
  - name: install base tools
    apt:
      name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
        - iperf3
      state: present
      update_cache: true

- name: Mode setting server
  hosts: ras_serv
  become: yes
  tasks:
  - name: mode setting
    copy:
      src: "../configs/server_{{ mode }}.conf"
      dest: /etc/openvpn/server.conf
  - name: 'Start OpenVPN server'
    systemd:
      name: openvpn@server
      state: restarted
      enabled: yes
      
- name: Mode setting client
  hosts: ras_client
  become: yes
  tasks:
  - name: mode setting
    copy:
      remote_src: True
      src: "../configs/client_{{ mode }}.conf"
      dest: /etc/openvpn/client.conf
  - name: 'Start OpenVPN server'
    systemd:
      name: openvpn@client
      state: restarted
      enabled: yes