---

- name: Update the repository cache and update package "nginx"
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
    

- name: update nginx config
  ansible.builtin.template:
    src: ../templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
  become: yes

- name: Enable a nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: started
    enabled: true